controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    meca_velocity_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Notice that this is OUTSIDE the controller_manager block
meca_velocity_controller:
  ros__parameters:
  
    joints:
      - meca_axis_1
      - meca_axis_2
      - meca_axis_3
      - meca_axis_4
      - meca_axis_5
      - meca_axis_6
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      meca_axis_1: {p: 1.0, i: 0.0, d: 0.0, ff_velocity_scale: 1.0, u_clamp_max: 3.70, u_clamp_min: -3.70}
      meca_axis_2: {p: 1.0, i: 0.0, d: 0.0, ff_velocity_scale: 1.0, u_clamp_max: 3.70, u_clamp_min: -3.70}
      meca_axis_3: {p: 1.0, i: 0.0, d: 0.0, ff_velocity_scale: 1.0, u_clamp_max: 3.70, u_clamp_min: -3.70}
      meca_axis_4: {p: 1.0, i: 0.0, d: 0.0, ff_velocity_scale: 1.0, u_clamp_max: 5.80, u_clamp_min: -5.80}
      meca_axis_5: {p: 1.0, i: 0.0, d: 0.0, ff_velocity_scale: 1.0, u_clamp_max: 5.80, u_clamp_min: -5.80}
      meca_axis_6: {p: 1.0, i: 0.0, d: 0.0, ff_velocity_scale: 1.0, u_clamp_max: 8.40, u_clamp_min: -8.40}